name = "logging_helper"
version = "1.0.0"
description = "Python Library to quickly create logging handlers"
license = "MIT"
authors = [
    "Thomas Dunteman <git@learningtopi.com>"
]
repository = "https://github.com/LearningToPi/logging_helper"
keywords = ["logging", "syslog"]

[tool.poetry]
readme = "README.md"
classifiers = [
    "Topic :: System :: Logging",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent"
]

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/LearningToPi/logging_helper/issues"

[build-system]
requires = ["setuptools>=42"]
build-backend = "setuptools.build_meta"